# Generated by Django 5.1.7 on 2025-03-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_usertask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='is_completed',
        ),
    ]
